# =============================================================================
# ⚙️ WRANGLER CONFIG - CHECKING OOH (ATUALIZADO)
# =============================================================================

name = "checking-ooh"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Configuração do Pages
pages_build_output_dir = "."

# Variáveis de desenvolvimento local (opcional)
[vars]
ENVIRONMENT = "development"

# Configuração de Workers (se necessário no futuro)
[env.production]
name = "checking-ooh-production"

[env.staging]
name = "checking-ooh-staging"

# Configurações específicas do Cloudflare Pages
[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js"]
headers = { "Cache-Control" = "public, max-age=86400" }

[[rules]]
type = "Text"  
globs = ["/api/*"]
headers = { "Cache-Control" = "no-store, no-cache, must-revalidate" }

# Build settings para Pages
[build]
command = "echo 'No build required'"
cwd = "."
watch_dir = "."

# Node.js compatibility
node_compat = true
