name = "checkingooh"
compatibility_date = "2024-03-08"
pages_build_output_dir = "."

[env.production]
compatibility_date = "2024-03-08"

[[env.production.vars]]
name = "NODE_ENV"
value = "production"

[build]
command = ""
cwd = ""
watch_dir = ""

[vars]
NODE_ENV = "development"
