name = "checkingooh"
compatibility_date = "2024-10-17"

[env.production.vars]
NODE_ENV = "production"
PROJECT_VERSION = "v3.1-estrutura-corrigida"

[vars]
NODE_ENV = "development"
PROJECT_VERSION = "v3.1-estrutura-corrigida"
