name = "checking-ooh"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./"

# Configuração para Cloudflare Pages
[env.production]
name = "checking-ooh"

# Variáveis de ambiente (configure no dashboard)
[env.production.vars]
# Configure essas variáveis no dashboard do Cloudflare Pages:
# Settings > Environment Variables > Production

# NOTION_TOKEN = "secret_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# NOTION_DATABASE_ID = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# GOOGLE_DRIVE_API_KEY = "AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" (opcional)
# GOOGLE_SERVICE_ACCOUNT_KEY = '{"type":"service_account",...}' (recomendado)
# GOOGLE_DRIVE_FOLDER_ID = "1XXXXXXXXXXXXXXXXXXXXXXXXXXXX" (opcional - padrão: root)

# Configuração de desenvolvimento
[env.development]
name = "checking-ooh-dev"

[env.development.vars]
# Mesmas variáveis que production para desenvolvimento
